const $=id=>document.getElementById(id);
const state={creator:null,demo:true};
const commercial=$('commercial'), own=$('ownBrand'), branded=$('branded');
commercial.addEventListener('change',()=>{$('commercialChoices').hidden=!commercial.checked;if(!commercial.checked){own.checked=false;branded.checked=false}update()});
[own,branded,$('privacy'),$('musicConsent'),$('exactPostConsent')].forEach(el=>el.addEventListener('change',update));
$('connectBtn').addEventListener('click',()=>location.assign('/api/tiktok/oauth/start'));
$('disconnectBtn').addEventListener('click',async()=>{if(!confirm('Disconnect TikTok and revoke Wright Drafts access?'))return;await fetch('/api/tiktok/revoke',{method:'POST'});location.reload()});
$('postForm').addEventListener('submit',async e=>{e.preventDefault();if(!update())return;const body={caption:$('caption').value,privacy_level:$('privacy').value,disable_comment:!$('comments').checked,auto_add_music:$('autoMusic').checked,brand_organic_toggle:own.checked,brand_content_toggle:branded.checked,consent:true};$('postBtn').disabled=true;$('status').textContent='Sending approved post…';const r=await fetch('/api/tiktok/direct-post',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok){$('status').textContent=data.error||'Posting failed.';update();return}$('status').textContent='Processing on TikTok…';poll(data.publish_id)});
function update(){const disclosureOk=!commercial.checked||own.checked||branded.checked;$('disclosureError').hidden=disclosureOk;const ready=state.creator&&$('privacy').value&&disclosureOk&&$('musicConsent').checked&&$('exactPostConsent').checked&&!state.demo;$('postBtn').disabled=!ready;return ready}
async function poll(id){const t=setInterval(async()=>{const r=await fetch('/api/tiktok/status?publish_id='+encodeURIComponent(id));const d=await r.json();$('status').textContent=d.status||'Checking status…';if(d.done||!r.ok)clearInterval(t)},2500)}
(async()=>{try{const r=await fetch('/api/tiktok/creator-info');if(!r.ok)return;const d=await r.json();state.creator=d;$('creatorName').textContent='@'+(d.creator_username||d.creator_nickname);$('connectBtn').hidden=true;$('disconnectBtn').disabled=false;for(const p of d.privacy_level_options||[]){const o=document.createElement('option');o.value=p;o.textContent=p.replaceAll('_',' ').toLowerCase();$('privacy').append(o)}$('status').textContent=state.demo?'Demo carousel already posted. Load a new approved carousel to enable posting.':'Choose settings and approve this exact post.';update()}catch{}})();
