const $=id=>document.getElementById(id);
const state={creator:null,demo:true};
const commercial=$('commercial'), own=$('ownBrand'), branded=$('branded');
commercial.addEventListener('change',()=>{$('commercialChoices').hidden=!commercial.checked;if(!commercial.checked){own.checked=false;branded.checked=false}update()});
[own,branded,$('privacy'),$('musicConsent'),$('exactPostConsent')].forEach(el=>el.addEventListener('change',update));
$('connectBtn').addEventListener('click',startDesktopPair);
async function startDesktopPair(){const btn=$('connectBtn');btn.disabled=true;btn.textContent='Creating secure link…';try{const r=await fetch('/api/pair/create',{method:'POST'}),p=await r.json();if(!r.ok)throw Error(p.error||'Could not create link');const box=document.createElement('div');box.className='card';box.innerHTML='<p class="label">Open on a computer</p><p>This one-time link expires in 10 minutes. TikTok signs in on the computer; no token is in the link.</p><p><a class="secondary" target="_blank" rel="noopener" href="'+p.desktop_url+'">'+p.desktop_url+'</a></p><button type="button" class="ghost" id="copyPair">Copy desktop link</button><p id="pairStatus" role="status">Waiting for TikTok approval on the computer…</p>';$('connectBtn').closest('section').after(box);$('copyPair').onclick=async()=>{await navigator.clipboard.writeText(p.desktop_url);$('copyPair').textContent='Copied'};const until=Date.now()+p.expires_in*1000;const timer=setInterval(async()=>{if(Date.now()>until){clearInterval(timer);$('pairStatus').textContent='Link expired. Create a new one.';btn.disabled=false;btn.textContent='Connect TikTok';return}const c=await fetch('/api/pair/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pair_id:p.pair_id,claim_secret:p.claim_secret})});if(c.status===200){clearInterval(timer);p.claim_secret='';$('pairStatus').textContent='TikTok connected. Reloading…';location.assign('/direct-post-ui/workspace.html')}},2500)}catch(e){btn.disabled=false;btn.textContent='Connect TikTok';$('status').textContent=e.message}}
$('disconnectBtn').addEventListener('click',async()=>{if(!confirm('Disconnect TikTok and revoke Wright Drafts access?'))return;await fetch('/api/tiktok/revoke',{method:'POST'});location.reload()});
$('postForm').addEventListener('submit',async e=>{e.preventDefault();if(!update())return;const body={caption:$('caption').value,privacy_level:$('privacy').value,disable_comment:!$('comments').checked,auto_add_music:$('autoMusic').checked,brand_organic_toggle:own.checked,brand_content_toggle:branded.checked,consent:true};$('postBtn').disabled=true;$('status').textContent='Sending approved post…';const r=await fetch('/api/tiktok/direct-post',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok){$('status').textContent=data.error||'Posting failed.';update();return}$('status').textContent='Processing on TikTok…';poll(data.publish_id)});
function update(){const disclosureOk=!commercial.checked||own.checked||branded.checked;$('disclosureError').hidden=disclosureOk;const ready=state.creator&&$('privacy').value&&disclosureOk&&$('musicConsent').checked&&$('exactPostConsent').checked&&!state.demo;$('postBtn').disabled=!ready;return ready}
async function poll(id){const t=setInterval(async()=>{const r=await fetch('/api/tiktok/status?publish_id='+encodeURIComponent(id));const d=await r.json();$('status').textContent=d.status||'Checking status…';if(d.done||!r.ok)clearInterval(t)},2500)}
(async()=>{try{const r=await fetch('/api/tiktok/creator-info');if(!r.ok)return;const d=await r.json();state.creator=d;$('creatorName').textContent='@'+(d.creator_username||d.creator_nickname);$('connectBtn').hidden=true;$('disconnectBtn').disabled=false;for(const p of d.privacy_level_options||[]){const o=document.createElement('option');o.value=p;o.textContent=p.replaceAll('_',' ').toLowerCase();$('privacy').append(o)}$('status').textContent=state.demo?'Demo carousel already posted. Load a new approved carousel to enable posting.':'Choose settings and approve this exact post.';update()}catch{}})();
