const $=id=>document.getElementById(id);let creator,posts=[],focus=false;
$('connectBtn').onclick=()=>location.assign('/api/tiktok/oauth/start');
$('disconnectBtn').onclick=async()=>{if(confirm('Disconnect TikTok and revoke Wright Drafts access?')){await fetch('/api/tiktok/revoke',{method:'POST'});location.reload()}};
$('batchConsent').onchange=update;$('focusMode').onclick=()=>{focus=!focus;document.body.classList.toggle('focus-mode',focus);$('focusMode').textContent=focus?'Show all posts':'Focus mode';updateFocus()};
$('approveBatch').onclick=async()=>{const selected=posts.filter(p=>document.querySelector(`[data-approve="${p.id}"]`)?.checked).map(readPost);if(!selected.length||!$('batchConsent').checked)return;$('approveBatch').disabled=true;$('status').textContent='Saving exact approvals…';const r=await fetch('/api/queue/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({posts:selected,batch_consent:true})});const d=await r.json();$('status').textContent=r.ok?`${selected.length} exact post${selected.length===1?'':'s'} approved for the shown times.`:(d.error||'Approval failed.');if(!r.ok)update()};
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function card(p,i){const pics=p.photo_images.map((src,j)=>`<figure><img src="${esc(src)}" alt="Post ${i+1}, slide ${j+1}"><figcaption>${j+1}</figcaption></figure>`).join('');return `<article class="post-card" data-id="${esc(p.id)}"><header><p class="label">Post ${i+1}</p><h2>${esc(p.name||'Finished carousel')}</h2></header><div class="slides">${pics}</div><div class="post-settings"><p class="label">Caption</p><p class="caption-preview">${esc(p.caption)}</p>${p.research?`<details class="research-details"><summary>Research and reasoning</summary><p>${esc(p.research.thesis||'')}</p><ul>${(p.research.sources||[]).map(u=>`<li><a href="${esc(u)}" target="_blank" rel="noopener">${esc(new URL(u).hostname.replace('www.',''))}</a></li>`).join('')}</ul><p class="hint">Use these sources to check the argument. Approval still covers only this exact post.</p></details>`:''}<label>Privacy <span class="required">Required</span><select data-field="privacy"><option value="" disabled>Choose privacy</option>${(creator.privacy_level_options||[]).map(x=>`<option value="${x}" ${x==='PUBLIC_TO_EVERYONE'?'selected':''}>${x==='PUBLIC_TO_EVERYONE'?'Public':x.replaceAll('_',' ').toLowerCase()}</option>`).join('')}</select></label><label class="check"><input type="checkbox" data-field="comments" checked> Allow comments</label><label class="check"><input type="checkbox" data-field="autoMusic" checked> Let TikTok add fitting recommended music</label><label class="check"><input type="checkbox" data-field="commercial"> This promotes a brand, product, or service</label><div class="schedule"><label>Date<input type="date" data-field="date" value="${esc(p.suggested_date||'')}"></label><label>Time<input type="time" data-field="time" value="${esc(p.suggested_time||'')}"></label></div></div><label class="check approve-one"><input type="checkbox" data-approve="${esc(p.id)}"> I approve this exact post and shown schedule</label></article>`}
function readPost(p){const root=document.querySelector(`[data-id="${CSS.escape(p.id)}"]`),privacy=root.querySelector('[data-field=privacy]').value,date=root.querySelector('[data-field=date]').value,time=root.querySelector('[data-field=time]').value;return {id:p.id,version:p.version,privacy_level:privacy,disable_comment:!root.querySelector('[data-field=comments]').checked,auto_add_music:root.querySelector('[data-field=autoMusic]').checked,commercial:root.querySelector('[data-field=commercial]').checked,scheduled_at_local:`${date}T${time}`,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,explicit_post_consent:true}}
function updateFocus(){const cards=[...document.querySelectorAll('.post-card')],selected=cards.findIndex(c=>c.querySelector('[data-approve]')?.checked),idx=selected>=0?selected:0;cards.forEach((c,i)=>c.hidden=focus&&i!==idx)}
function update(){const checks=[...document.querySelectorAll('[data-approve]')],selected=checks.filter(x=>x.checked);$('selectionSummary').textContent=`${selected.length} post${selected.length===1?'':'s'} selected.`;let valid=selected.length>0&&$('batchConsent').checked;for(const c of selected){const root=c.closest('.post-card');valid&&=!!root.querySelector('[data-field=privacy]').value&&!!root.querySelector('[data-field=date]').value&&!!root.querySelector('[data-field=time]').value}$('approveBatch').disabled=!valid;updateFocus()}
(async()=>{try{const [cr,qr]=await Promise.all([fetch('/api/tiktok/creator-info'),fetch('/api/queue')]);if(!cr.ok)return;creator=await cr.json();$('creatorName').textContent='@'+(creator.creator_username||creator.creator_nickname);$('connectBtn').hidden=true;$('disconnectBtn').disabled=false;if(qr.ok){posts=(await qr.json()).posts||[];$('queueCount').textContent=`${posts.length} finished post${posts.length===1?'':'s'} waiting`;$('queue').innerHTML=posts.length?posts.map(card).join(''):'<section class="card"><h2>No finished posts waiting</h2><p class="hint">New posts appear here only after the carousel, caption, settings, and proposed posting time are finished.</p></section>';document.querySelectorAll('input,select').forEach(x=>x.addEventListener('change',update));update()}}catch{}})();
