const $=id=>document.getElementById(id);let all=[],filter='all';const labels={draft:'Draft',ready:'Ready for review',approved:'Scheduled',processing:'Processing',published:'Published',failed:'Needs attention'};
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalized(p,history=false){return {...p,state:p.state||(history?'published':'draft'),when:p.published_at||p.submitted_at||p.approval?.approved_at||p.updated_at||'',history}}
function render(){let q=$('search').value.toLowerCase(),items=all.filter(p=>(filter==='all'||p.state===filter)&&(!q||[p.name,p.caption,p.state].join(' ').toLowerCase().includes(q)));items.sort((a,b)=>$('sort').value==='status'?a.state.localeCompare(b.state):$('sort').value==='oldest'?(a.when||'').localeCompare(b.when||''):(b.when||'').localeCompare(a.when||''));$('grid').innerHTML=items.length?items.map(card).join(''):'<div class="card empty"><h2>Nothing here yet</h2><p>Finished posts appear only when their content and settings are ready.</p></div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open))}
function card(p){const img=p.photo_images?.[0]||'',status=labels[p.state]||p.state;return `<article class="content-card"><button class="card-open" data-open="${esc(p.id)}" aria-label="Open ${esc(p.name||'post')}"><div class="cover">${img?`<img src="${esc(img)}" alt="">`:'<span>No preview</span>'}<span class="status ${esc(p.state)}">${esc(status)}</span><span class="slides-count">${p.photo_images?.length||0} slides</span></div><div class="content-meta"><h2>${esc(p.name||'Untitled carousel')}</h2>${p.research?'<span class=research-mark>Research attached</span>':''}<p>${esc(p.caption||'No caption saved')}</p><div class="meta-row"><span>${esc(displayTime(p))}</span><span>${esc(p.privacy_level||p.approval?.privacy_level||'Privacy pending')}</span></div></div></button></article>`}
function displayTime(p){if(p.published_at)return 'Published '+new Date(p.published_at).toLocaleDateString();if(p.approval?.scheduled_at_local)return 'Scheduled '+p.approval.scheduled_at_local.replace('T',' ');if(p.suggested_date)return 'Suggested '+p.suggested_date+' '+(p.suggested_time||'');if(p.submitted_at)return 'Submitted '+new Date(p.submitted_at).toLocaleString();return labels[p.state]||''}
function open(id){const p=all.find(x=>x.id===id);if(!p)return;const pics=(p.photo_images||[]).map((src,i)=>`<figure><img src="${esc(src)}" alt="Slide ${i+1}"><figcaption>${i+1}</figcaption></figure>`).join('');$('detailBody').innerHTML=`<p class="eyebrow">${esc(labels[p.state]||p.state)}</p><h1>${esc(p.name||'Untitled carousel')}</h1><div class="slides">${pics}</div><dl class="detail-list"><div><dt>Caption</dt><dd>${esc(p.caption||'Not saved')}</dd></div><div><dt>Timing</dt><dd>${esc(displayTime(p))}</dd></div><div><dt>Privacy</dt><dd>${esc(p.privacy_level||p.approval?.privacy_level||'Pending')}</dd></div><div><dt>Music</dt><dd>${p.auto_add_music||p.approval?.auto_add_music?'Recommended auto-music on':'Not selected'}</dd></div><div><dt>Version</dt><dd>${esc(p.version||'Published record')}</dd></div>${p.publish_id?`<div><dt>Publish ID</dt><dd class="mono">${esc(p.publish_id)}</dd></div>`:''}</dl>${p.research?`<section class="research-panel"><p class="label">Why this post</p><h2>${esc(p.research.thesis||'Research rationale')}</h2><ol>${(p.research.sources||[]).map(u=>`<li><a href="${esc(u)}" target="_blank" rel="noopener">${esc(new URL(u).hostname.replace('www.',''))}</a></li>`).join('')}</ol><p class="hint">Sources explain the argument. They do not prove future performance.</p></section>`:''}${p.state==='ready'?'<p class="chat-command">To act: message “Post '+esc(p.name||'this post')+' now with defaults” or name a local date and time.</p>':''}`;$('details').showModal()}
function counts(){for(const s of ['draft','ready','approved','published'])$(s==='approved'?'scheduledCount':s+'Count').textContent=all.filter(p=>p.state===s).length}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>{document.querySelector('.tab.active').classList.remove('active');x.classList.add('active');filter=x.dataset.view;render()});$('search').oninput=render;$('sort').onchange=render;document.querySelector('.dialog-close').onclick=()=>$('details').close();
(async()=>{const r=await fetch('/api/workspace');if(!r.ok){$('connectionNotice').hidden=false;$('accountName').textContent='TikTok not connected';$('grid').innerHTML='<div class="card"><h2>Connect TikTok to load your workspace</h2></div>';return}const d=await r.json();$('accountName').textContent='TikTok connected';all=[...(d.posts||[]).map(x=>normalized(x)),...(d.history||[]).map(x=>normalized(x,true))];counts();render()})().catch(()=>{$('grid').innerHTML='<div class="card"><h2>Workspace could not load</h2><p>Refresh or check the connection.</p></div>'});
