// Wright Drafts Direct Post backend. Secrets: TIKTOK_CLIENT_KEY, TIKTOK_CLIENT_SECRET.
const TT='https://open.tiktokapis.com',PAIR_TTL=600;
export default {async fetch(req,env){const u=new URL(req.url);try{
 if(u.pathname==='/api/pair/create'&&req.method==='POST')return pairCreate(req,env);
 if(u.pathname==='/api/pair/claim'&&req.method==='POST')return pairClaim(req,env);
 if(u.pathname==='/pair/desktop'&&req.method==='GET')return pairDesktop(u);
 if(u.pathname==='/api/pair/oauth/start'&&req.method==='GET')return pairOauthStart(req,env);
 if(u.pathname==='/api/tiktok/oauth/start')return oauthStart(req,env);
 if(u.pathname==='/api/tiktok/oauth/callback')return oauthCallback(req,env);
 if(u.pathname==='/api/operator/execute'&&req.method==='POST')return operatorExecute(req,env);
 if(u.pathname==='/api/operator/restore'&&req.method==='POST')return operatorRestore(req,env);
 if(u.pathname==='/api/operator/status'&&req.method==='GET')return operatorStatus(req,env);
 if(u.pathname==='/api/operator/asset'&&req.method==='POST')return operatorAsset(req,env);
 if(u.pathname==='/api/operator/prepare-v3'&&req.method==='POST')return operatorPrepareV3(req,env);
 if(u.pathname==='/media/immutable/tiktokYu4WAfbl6ij3EFs6jQ42S3VlZr2llDBD.txt'&&req.method==='GET')return new Response('tiktok-developers-site-verification=Yu4WAfbl6ij3EFs6jQ42S3VlZr2llDBD',{headers:{'content-type':'text/plain; charset=utf-8','cache-control':'public, max-age=300'}});
 if(u.pathname.startsWith('/media/immutable/')&&req.method==='GET')return immutableAsset(u,env);
 if(u.pathname==='/api/operator/spec'&&req.method==='GET')return operatorSpec(req,env);
 if(req.method==='GET'&&!u.pathname.startsWith('/api/'))return fetch('https://ceomo30-lab.github.io/wright-tiktok-drafts'+u.pathname+u.search);
 let session=await getSession(req,env);if(!session&&['/api/workspace','/api/queue','/api/tiktok/creator-info'].includes(u.pathname))session=await primaryAccount(env);if(!session)return json({error:'Connect TikTok first'},401);
 if(u.pathname==='/api/tiktok/creator-info'&&req.method==='GET')return creatorInfo(session);
 if(u.pathname==='/api/tiktok/direct-post'&&req.method==='POST')return directPost(req,session,env);
 if(u.pathname==='/api/tiktok/status'&&req.method==='GET')return postStatus(u,session);
 if(u.pathname==='/api/tiktok/revoke'&&req.method==='POST')return revoke(session,env);
 if(u.pathname==='/api/workspace'&&req.method==='GET')return workspace(session,env);
 if(u.pathname==='/api/seed/wright-02'&&req.method==='POST')return seedWright02(req,session,env);
 if(u.pathname==='/api/queue'&&req.method==='GET')return queueList(session,env);
 if(u.pathname==='/api/queue/approve'&&req.method==='POST')return queueApprove(req,session,env);
 if(u.pathname==='/api/queue/reorder'&&req.method==='POST')return queueReorder(req,session,env);
 return json({error:'Not found'},404);
 }catch(e){console.error(e);return json({error:'Request failed'},500)}}};

export class PairCoordinator{constructor(state){this.state=state}async fetch(req){const u=new URL(req.url),now=Date.now();if(req.method==='POST'&&u.pathname==='/init'){const b=await req.json(),old=await this.state.storage.get('pair');if(old&&old.expires>now)return json({error:'Pair already exists'},409);await this.state.storage.put('pair',{claim_hash:b.claim_hash,expires:now+PAIR_TTL*1000,status:'pending'});await this.state.storage.setAlarm(now+PAIR_TTL*1000);return json({ok:true})}if(req.method==='POST'&&u.pathname==='/complete'){const b=await req.json(),p=await this.state.storage.get('pair');if(!p||p.expires<=now||p.status!=='pending')return json({error:'Pair unavailable'},409);p.status='complete';p.token=b.token;await this.state.storage.put('pair',p);return json({ok:true})}if(req.method==='POST'&&u.pathname==='/claim'){const b=await req.json(),p=await this.state.storage.get('pair');if(!p||p.expires<=now||p.status!=='complete'||!safeEq(p.claim_hash,b.claim_hash))return json({error:'Pair not ready'},409);const token=p.token;await this.state.storage.deleteAll();return json({token})}return json({error:'Not found'},404)}async alarm(){await this.state.storage.deleteAll()}}

async function pairCreate(req,env){if(!sameOrigin(req))return json({error:'Bad origin'},403);if(!await rate(req,env,'create',5))return json({error:'Too many pairing attempts'},429);const pair=id(24),secret=id(32),hash=await sha(secret),stub=env.PAIR_COORDINATOR.getByName(pair);const r=await stub.fetch('https://pair/init',{method:'POST',body:JSON.stringify({claim_hash:hash})});if(!r.ok)return json({error:'Could not create pair'},409);const base=new URL(req.url).origin;return json({pair_id:pair,claim_secret:secret,desktop_url:`${base}/pair/desktop?pair=${encodeURIComponent(pair)}`,expires_in:PAIR_TTL})}
async function pairClaim(req,env){if(!sameOrigin(req))return json({error:'Bad origin'},403);if(!await rate(req,env,'claim',30))return json({error:'Too many claim attempts'},429);const b=await req.json();if(!validId(b.pair_id)||!validId(b.claim_secret))return json({error:'Invalid pair'},400);const stub=env.PAIR_COORDINATOR.getByName(b.pair_id),r=await stub.fetch('https://pair/claim',{method:'POST',body:JSON.stringify({claim_hash:await sha(b.claim_secret)})});if(!r.ok)return json({pending:true},202);const out=await r.json(),sessionId=id(32);await env.SESSIONS.put('session:'+sessionId,JSON.stringify(out.token),{expirationTtl:out.token.refresh_expires_in||31536000});return new Response(JSON.stringify({connected:true}),{headers:{'content-type':'application/json','cache-control':'no-store','set-cookie':cookie('session',sessionId,out.token.refresh_expires_in||31536000)}})}
function pairDesktop(u){const p=u.searchParams.get('pair');if(!validId(p))return html('<h1>Invalid or expired link</h1>',400);return html(`<main><p>WRIGHT DRAFTS</p><h1>Connect TikTok on this computer</h1><p>This one-time link expires in 10 minutes. Your TikTok tokens never appear in this link.</p><a class="btn" href="/api/pair/oauth/start?pair=${encodeURIComponent(p)}">Continue with TikTok</a></main>`)}
async function pairOauthStart(req,env){const u=new URL(req.url),pair=u.searchParams.get('pair');if(!validId(pair)||!await rate(req,env,'oauth',10))return html('<h1>Invalid or expired link</h1>',400);const state=id(32),redirect=new URL('/api/tiktok/oauth/callback',req.url).href;await env.SESSIONS.put('pair-state:'+state,JSON.stringify({pair,redirect}),{expirationTtl:PAIR_TTL});const q=new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,scope:'user.info.basic,video.publish,video.upload',response_type:'code',redirect_uri:redirect,state,disable_auto_auth:'1'});return Response.redirect('https://www.tiktok.com/v2/auth/authorize/?'+q,302)}
async function oauthStart(req,env){const state=crypto.randomUUID(),sid=crypto.randomUUID();await env.SESSIONS.put('oauth:'+sid,JSON.stringify({state}),{expirationTtl:600});const redirect=new URL('/api/tiktok/oauth/callback',req.url).href;const q=new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,scope:'user.info.basic,video.publish,video.upload',response_type:'code',redirect_uri:redirect,state,disable_auto_auth:'1'});return new Response(null,{status:302,headers:{location:'https://www.tiktok.com/v2/auth/authorize/?'+q,'set-cookie':cookie('oauth',sid,600)}})}
async function oauthCallback(req,env){const u=new URL(req.url),state=u.searchParams.get('state'),pairRec=state&&await env.SESSIONS.get('pair-state:'+state,'json');if(pairRec){await env.SESSIONS.delete('pair-state:'+state);const tok=await exchange(u,env,pairRec.redirect);if(tok.error)return json(tok,400);await savePrimaryAccount(env,tok);const r=await env.PAIR_COORDINATOR.getByName(pairRec.pair).fetch('https://pair/complete',{method:'POST',body:JSON.stringify({token:tok})});return r.ok?html('<main><h1>TikTok connected</h1><p>Return to your phone. This window can be closed.</p></main>'):html('<h1>This link expired</h1>',409)}const sid=cookies(req).oauth,rec=sid&&await env.SESSIONS.get('oauth:'+sid,'json');if(!rec||rec.state!==state)return json({error:'Invalid OAuth state'},400);const redirect=new URL('/api/tiktok/oauth/callback',req.url).href,tok=await exchange(u,env,redirect);if(tok.error)return json(tok,400);await savePrimaryAccount(env,tok);const sessionId=id(32);await env.SESSIONS.put('session:'+sessionId,JSON.stringify(tok),{expirationTtl:tok.refresh_expires_in||31536000});return new Response(null,{status:302,headers:{location:'/direct-post-ui/','set-cookie':cookie('session',sessionId,tok.refresh_expires_in||31536000)}})}
async function exchange(u,env,redirect){const form=new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,client_secret:env.TIKTOK_CLIENT_SECRET,code:u.searchParams.get('code')||'',grant_type:'authorization_code',redirect_uri:redirect});const r=await fetch(TT+'/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});const x=await r.json();if(r.ok&&x.access_token){x.expires_at=Math.floor(Date.now()/1000)+(x.expires_in||86400);return x}return {error:'TikTok authorization failed'}}
async function cryptKey(env){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(env.TIKTOK_CLIENT_SECRET+'|wright-primary-v1')),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(env,x){const iv=crypto.getRandomValues(new Uint8Array(12)),buf=await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptKey(env),new TextEncoder().encode(JSON.stringify(x)));return {iv:b64(iv),data:b64(new Uint8Array(buf))}}
async function unseal(env,x){try{const buf=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(x.iv)},await cryptKey(env),unb64(x.data));return JSON.parse(new TextDecoder().decode(buf))}catch{return null}}
async function savePrimaryAccount(env,tok){await env.SESSIONS.put('primary-account',JSON.stringify(await seal(env,{...tok,saved_at:Date.now()})))}
async function primaryAccount(env){const x=await env.SESSIONS.get('primary-account','json');return x&&unseal(env,x)}
async function operatorAuth(req,env){const auth=req.headers.get('authorization')||'';return !!env.OPERATOR_KEY&&safeEq(auth,'Bearer '+env.OPERATOR_KEY)}
async function operatorRestore(req,env){if(!await operatorAuth(req,env))return json({error:'Unauthorized'},401);const b=await req.json();if(!b.refresh_token)return json({error:'refresh_token required'},400);const r=await fetch(TT+'/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,client_secret:env.TIKTOK_CLIENT_SECRET,grant_type:'refresh_token',refresh_token:b.refresh_token})}),x=await r.json();if(!r.ok||!x.access_token)return json({error:'TikTok refresh failed'},409);x.expires_at=Math.floor(Date.now()/1000)+(x.expires_in||86400);await savePrimaryAccount(env,x);const ci=await tt('/v2/post/publish/creator_info/query/',{},x);return json({restored:ci.ok,account:{open_id:x.open_id,creator_username:ci.body.data?.creator_username||null},scopes:x.scope||''},ci.ok?200:409)}
async function operatorSpec(req,env){if(!await operatorAuth(req,env))return json({error:'Unauthorized'},401);const q=await env.POSTS.get('queue','json')||{posts:[]},s=await primaryAccount(env);return json({account_open_id:s?.open_id||null,defaults:{privacy_level:'PUBLIC_TO_EVERYONE',disable_comment:false,auto_add_music:true,commercial:false,timezone:'America/Los_Angeles'},posts:await Promise.all(q.posts.filter(p=>p.state==='ready').map(async p=>({id:p.id,version:p.version,name:p.name,caption:p.caption,caption_sha256:await sha(p.caption||''),suggested_date:p.suggested_date,suggested_time:p.suggested_time})))})}
async function operatorAsset(req,env){if(!await operatorAuth(req,env))return json({error:'Unauthorized'},401);const b=await req.json(),name=(b.name||'').replace(/[^a-zA-Z0-9._-]/g,'');if(!/^wright-03d-0[1-5]\.jpg$/.test(name)||!b.data||b.mime!=='image/jpeg'||!b.sha256)return json({error:'Invalid immutable asset'},400);const bytes=Uint8Array.from(atob(b.data),c=>c.charCodeAt(0)),digest=await shaBytes(bytes);if(digest!==b.sha256)return json({error:'SHA-256 mismatch'},409);const key='asset:'+name,existing=await env.POSTS.get(key,'json');if(existing&&existing.sha256!==digest)return json({error:'Immutable name already used'},409);await env.POSTS.put(key,JSON.stringify({name,mime:b.mime,sha256:digest,width:b.width,height:b.height,data:b.data,saved_at:new Date().toISOString()}));return json({stored:true,name,sha256:digest,url:'/media/immutable/'+name})}
async function operatorPrepareV3(req,env){if(!await operatorAuth(req,env))return json({error:'Unauthorized'},401);const names=[1,2,3,4,5].map(i=>'wright-03d-0'+i+'.jpg');for(const name of names)if(!await env.POSTS.get('asset:'+name))return json({error:'Missing immutable asset '+name},409);const q=await env.POSTS.get('queue','json')||{posts:[]},source=q.posts.find(x=>x.id==='wright-03-visible-judgment-compliant'&&x.version==='v2-direct-post-compliant-2026-09-19T1213PDT');if(!source)return json({error:'Approved source version missing'},409);const id='wright-03-visible-judgment-compliant-jpeg',version='v3-direct-post-compliant-jpeg-2026-09-19T1230PDT',urls=names.map(name=>'https://wright-drafts-app.ceomo30.workers.dev/media/immutable/'+name),existing=q.posts.find(x=>x.id===id);if(existing&&existing.version!==version)return json({error:'Immutable post ID already used'},409);const post={...source,id,version,state:'ready',photo_images:urls,approval:null,publish_id:null,submitted_at:null,last_error:null,derived_from:{id:source.id,version:source.version,change:'JPEG transcoding only'},asset_sha256:['905242f6b8ef7d6c7b563d68daea4e534d38ea6ce358fdecd388ef3b0b86e2a5','1f0871100b3ec331e84bfb43d20a29b408809ee095335f5eab6b2f90688b65bc','a10b295bc06386f1e2b4a7b59eb819d76dcf7bf8b33b8ab61552a283c360af31','b640708777739a088a15b586bf65f61d209712c1c8165fe9c11d1961224232a2','1ae29482156cfdfbe43ba29dd84071921ce30ee38fc6aa4f89f898cf1d4bf62b']};if(existing)Object.assign(existing,post);else q.posts.unshift(post);await env.POSTS.put('queue',JSON.stringify(q));return json({prepared:true,id,version,caption_sha256:await sha(post.caption||''),photo_images:urls})}
async function immutableAsset(u,env){const name=u.pathname.split('/').pop(),a=await env.POSTS.get('asset:'+name,'json');if(!a)return json({error:'Not found'},404);const bytes=Uint8Array.from(atob(a.data),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'content-type':a.mime,'content-length':String(bytes.length),'cache-control':'public, max-age=31536000, immutable','etag':'"'+a.sha256+'"','x-content-type-options':'nosniff','x-asset-sha256':a.sha256}})}
async function shaBytes(bytes){const h=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function operatorStatus(req,env){if(!await operatorAuth(req,env))return json({error:'Unauthorized'},401);const s=await primaryAccount(env);if(!s)return json({connected:false});const u=new URL(req.url),publishId=u.searchParams.get('publish_id');if(publishId){const out=await tt('/v2/post/publish/status/fetch/',{publish_id:publishId},s),status=out.body.data?.status||out.body.error?.message;return json({publish_id:publishId,status,done:['PUBLISH_COMPLETE','FAILED'].includes(status),raw:out.body},out.ok?200:400)}const ci=await tt('/v2/post/publish/creator_info/query/',{},s);return json({connected:ci.ok,account:{open_id:s.open_id,creator_username:ci.body.data?.creator_username||null},scopes:s.scope||'',saved_at:s.saved_at||null},ci.ok?200:409)}
async function operatorExecute(req,env){if(!await operatorAuth(req,env))return json({error:'Unauthorized'},401);if(!await rate(req,env,'operator',20))return json({error:'Too many attempts'},429);const b=await req.json(),required=['post_id','version','caption_sha256','account_open_id','scheduled_at_local','timezone','authority_ref','action'];for(const k of required)if(!b[k])return json({error:'Missing '+k},400);b.privacy_level=b.privacy_level||'PUBLIC_TO_EVERYONE';if(!['approve','publish'].includes(b.action))return json({error:'Invalid action'},400);const q=await env.POSTS.get('queue','json')||{posts:[]},p=q.posts.find(x=>x.id===b.post_id);if(!p||p.version!==b.version||!['ready','approved','failed'].includes(p.state))return json({error:'Post/version is not reviewable'},409);if(await sha(p.caption||'')!==b.caption_sha256)return json({error:'Caption changed'},409);let s=await primaryAccount(env);if(!s)return json({error:'No durable TikTok account connection'},409);if(s.open_id!==b.account_open_id)return json({error:'TikTok account mismatch'},409);const ci=await tt('/v2/post/publish/creator_info/query/',{},s);if(!ci.ok||!ci.body.data?.privacy_level_options?.includes(b.privacy_level))return json({error:'Account connection or privacy option is no longer valid'},409);const exact={privacy_level:b.privacy_level,disable_comment:b.disable_comment===true,auto_add_music:b.auto_add_music!==false,brand_content_toggle:!!b.brand_content_toggle,brand_organic_toggle:!!b.brand_organic_toggle,commercial:!!b.commercial,scheduled_at_local:b.scheduled_at_local,timezone:b.timezone,caption:p.caption,caption_sha256:b.caption_sha256,account_open_id:b.account_open_id,authority_ref:b.authority_ref,approved_at:new Date().toISOString(),channel:'trusted-owner-text'};p.approval=exact;p.state='approved';await env.POSTS.put('queue',JSON.stringify(q));if(b.action==='approve')return json({approved:true,post_id:p.id,version:p.version,exact});const payload={media_type:'PHOTO',post_mode:'DIRECT_POST',is_aigc:!!p.is_aigc,post_info:{title:p.name||'',description:p.caption||'',privacy_level:b.privacy_level,disable_comment:b.disable_comment===true,auto_add_music:b.auto_add_music!==false,brand_content_toggle:!!b.brand_content_toggle,brand_organic_toggle:!!b.brand_organic_toggle},source_info:{source:'PULL_FROM_URL',photo_cover_index:p.cover_index||0,photo_images:p.photo_images}};const out=await tt('/v2/post/publish/content/init/',payload,s);if(!out.ok){p.state='failed';p.last_error=out.body;await env.POSTS.put('queue',JSON.stringify(q));return json({error:'TikTok submission failed',detail:out.body},400)}const pid=out.body.data?.publish_id;p.state='processing';p.publish_id=pid;p.submitted_at=new Date().toISOString();await env.POSTS.put('queue',JSON.stringify(q));await addHistory(env,{...p,id:p.id,state:'processing',publish_id:pid});return json({submitted:true,post_id:p.id,version:p.version,publish_id:pid,authority_ref:b.authority_ref})}
async function creatorInfo(s){const r=await tt('/v2/post/publish/creator_info/query/',{},s);return json(r.body,r.ok?200:400)}
async function directPost(req,s,env){const b=await req.json();if(b.consent!==true||!b.privacy_level)return json({error:'Exact post approval and privacy choice are required'},400);const ci=await tt('/v2/post/publish/creator_info/query/',{},s);if(!ci.ok||!ci.body.data?.privacy_level_options?.includes(b.privacy_level))return json({error:'Privacy choice is not currently available'},400);if(b.brand_content_toggle&&b.privacy_level==='SELF_ONLY')return json({error:'Branded content cannot be private'},400);const manifest=await env.POSTS.get('current','json');if(!manifest||manifest.approved!==true)return json({error:'No finished carousel is loaded'},409);const payload={media_type:'PHOTO',post_mode:'DIRECT_POST',is_aigc:!!manifest.is_aigc,post_info:{title:manifest.title||'',description:b.caption||'',privacy_level:b.privacy_level,disable_comment:b.disable_comment===true,auto_add_music:b.auto_add_music!==false,brand_content_toggle:!!b.brand_content_toggle,brand_organic_toggle:!!b.brand_organic_toggle},source_info:{source:'PULL_FROM_URL',photo_cover_index:manifest.cover_index||0,photo_images:manifest.photo_images}};const out=await tt('/v2/post/publish/content/init/',payload,s);if(out.ok){const pid=out.body.data?.publish_id;await addHistory(env,{id:'publish-'+pid,name:manifest.name||manifest.title||'TikTok carousel',caption:b.caption||'',state:'processing',submitted_at:new Date().toISOString(),publish_id:pid,photo_images:manifest.photo_images,privacy_level:b.privacy_level,auto_add_music:!!b.auto_add_music});}return json(out.ok?{publish_id:out.body.data?.publish_id}:out.body,out.ok?200:400)}
async function postStatus(u,s){const id=u.searchParams.get('publish_id');if(!id)return json({error:'publish_id required'},400);const out=await tt('/v2/post/publish/status/fetch/',{publish_id:id},s),status=out.body.data?.status||out.body.error?.message;return json({status,done:['PUBLISH_COMPLETE','FAILED'].includes(status),raw:out.body},out.ok?200:400)}
async function ensureWright02(env){const q=await env.POSTS.get('queue','json')||{posts:[]},id='wright-02-ai-steering';if(!q.posts.some(x=>x.id===id)){q.posts.unshift({id,version:'v1-2026-09-18T2306PDT',name:'AI autopilot vs. AI engine',caption:'AI helping a teen finish faster is not the same as a teen learning to think better. The difference is who makes the calls: defining the problem, directing the tool, testing the result, and choosing what happens next. Wright gives teens repeated practice steering.\n\n#ParentingTeens #AILiteracy #FutureSkills #WrightSchool',state:'ready',photo_images:['https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-01.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-02.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-03.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-04.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-05.png'],suggested_date:'2026-09-19',suggested_time:'12:00',research:{thesis:'The important difference is not AI access but whether the teen retains judgment.',sources:['https://www.unesco.org/en/articles/what-you-need-know-about-unescos-new-ai-competency-frameworks-students-and-teachers','https://www.oecd.org/en/about/projects/pisa-2029-media-and-artificial-intelligence-literacy.html','https://www.commonsensemedia.org/research/the-dawn-of-the-ai-era-teens-parents-and-the-adoption-of-generative-ai-at-home-and-school','https://www.microsoft.com/en-us/research/wp-content/uploads/2025/01/lee_2025_ai_critical_thinking_survey.pdf','https://wright.school/program']}});await env.POSTS.put('queue',JSON.stringify(q))}return q}
async function seedWright02(req,s,env){if(!sameOrigin(req))return json({error:'Bad origin'},403);const q=await ensureWright02(env);return json({created:true,id:'wright-02-ai-steering'})}
async function ensureWright03(env){const q=await env.POSTS.get('queue','json')||{posts:[]},id='wright-03-visible-judgment';if(!q.posts.some(x=>x.id===id)){q.posts.unshift({id,version:'v1-2026-09-19T0043PDT',name:'Completion log vs. Build Record',caption:'A green checkmark can tell you a teen finished. It cannot tell you what they can do when the instructions disappear. Compare completion with evidence: the problem they found, what failed, what changed, and what the evidence says to do next. That is the work a parent can actually inspect. Try one free challenge at wright.school/start.\n\n#ParentingTeens #ProjectBasedLearning #FutureSkills #WrightSchool',state:'ready',photo_images:['https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03/wright-03-01.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03/wright-03-02.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03/wright-03-03.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03/wright-03-04.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03/wright-03-05.png'],suggested_date:'2026-09-20',suggested_time:'12:00',research:{thesis:'Completion signals are not sufficient evidence of transfer; parents should inspect decisions and revisions.',sources:['https://pmc.ncbi.nlm.nih.gov/articles/PMC10411581/','https://www.nationalacademies.org/read/13398/chapter/8','https://www.oecd.org/en/data/tools/oecd-learning-compass-2030.html','https://wright.school/program']}});await env.POSTS.put('queue',JSON.stringify(q))}return q}
async function ensureWright04(env){const q=await env.POSTS.get('queue','json')||{posts:[]},id='wright-04-founder-origin';if(!q.posts.some(x=>x.id===id)){q.posts.unshift({id,version:'v1-2026-09-19T0106PDT',name:'Why Wright started',caption:'Wright started with Ibrahim’s 15-year-old brother, who had never built software. The realization was simple: access to AI was not the same as knowing what was worth making. So Wright starts with reality - a person, a problem, one useful promise - then puts AI to work. Try one free challenge and inspect the decision trail yourself at wright.school/start.\n\n#ParentingTeens #FounderStory #AILiteracy #WrightSchool',state:'ready',photo_images:['https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-04/wright-04-01.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-04/wright-04-02.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-04/wright-04-03.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-04/wright-04-04.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-04/wright-04-05.png'],suggested_date:'2026-09-21',suggested_time:'12:00',research:{thesis:'The founder origin is specific, credible, and connects the AI-access problem to Wright’s judgment-first mechanism and inspectable trial.',sources:['https://wright.school/about','https://wright.school/program','https://wright.school/start','https://www.commonsensemedia.org/research/the-dawn-of-the-ai-era-teens-parents-and-the-adoption-of-generative-ai-at-home-and-school','https://www.unesco.org/en/articles/what-you-need-know-about-unescos-new-ai-competency-frameworks-students-and-teachers']}});await env.POSTS.put('queue',JSON.stringify(q))}return q}
async function ensureWright05(env){const q=await env.POSTS.get('queue','json')||{posts:[]},id='wright-05-durable-skill-stack';if(!q.posts.some(x=>x.id===id)){q.posts.unshift({id,version:'v1-2026-09-19T0447PDT',name:'The skill stack that survives the next tool',caption:'Your teen’s best app may expire first. Platforms change, features copy each other, and today’s shortcut becomes tomorrow’s default button. The more durable stack is a way of thinking: observe, choose, direct, test, revise, explain. Wright gives teens a training ground for that stack. Try one free challenge at wright.school/start.\n\n#FutureSkills #ParentingTeens #AILiteracy #WrightSchool',state:'ready',photo_images:['https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-05/wright-05-01.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-05/wright-05-02.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-05/wright-05-03.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-05/wright-05-04.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-05/wright-05-05.png'],suggested_date:'2026-09-22',suggested_time:'12:00',research:{thesis:'Tool fluency matters, but a decision system is more durable as interfaces change and AI lowers the cost of producing options.',sources:['https://reports.weforum.org/docs/WEF_Future_of_Jobs_Report_2025.pdf','https://naceweb.org/research/reports/job-outlook/2025','https://www.oecd.org/en/publications/social-and-emotional-skills-for-better-lives_35ca7b7c-en/full-report/executive-summary_78f0e166.html','https://wright.school/program','https://wright.school/start']}});await env.POSTS.put('queue',JSON.stringify(q))}return q}
async function complianceMigration(env){const q=await env.POSTS.get('queue','json')||{posts:[]};for(const p of q.posts){if(['wright-02-ai-steering','wright-04-founder-origin','wright-05-durable-skill-stack'].includes(p.id)&&p.state!=='published'){p.state='blocked';p.block_reason='Direct Post watermark rule: remove brand names, URLs and promotional text before approval.'}}const id='wright-03-visible-judgment-compliant',old=q.posts.find(x=>x.id==='wright-03-visible-judgment');if(old&&old.state!=='published')old.state='blocked';if(!q.posts.some(x=>x.id===id))q.posts.unshift({id,version:'v2-direct-post-compliant-2026-09-19T1213PDT',name:'Completion log vs. Build Record',caption:'A green checkmark can tell you a teen finished. It cannot tell you what they can do when the instructions disappear. Compare completion with evidence: the problem they found, what failed, what changed, and what the evidence says to do next. What would you ask to see before treating completion as learning?\n\n#ParentingTeens #ProjectBasedLearning #FutureSkills',state:'ready',photo_images:['https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03c/wright-03c-01.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03c/wright-03c-02.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03c/wright-03c-03.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03c/wright-03c-04.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-03c/wright-03c-05.png'],suggested_date:'2026-09-19',suggested_time:'12:20',compliance:{watermark_free:true,no_links:true,no_brand_names:true,editorial_caption:true,brand_organic_required:false,checked_against:'https://developers.tiktok.com/docs/en/content-sharing-guidelines/'},research:old?.research||null});await env.POSTS.put('queue',JSON.stringify(q));return q}
async function workspace(s,env){await complianceMigration(env);await ensureWright02(env);await ensureWright03(env);await ensureWright04(env);const q=await ensureWright05(env),h=await env.POSTS.get('history','json')||{posts:[]};const existing={id:'posted-2026-09-18-ai-assignment',name:'AI can finish the assignment',caption:'',state:'published',published_at:'2026-09-18T19:45:00-07:00',publish_id:'p_inbox_url~v2.7687070275556755470',photo_images:['https://ceomo30-lab.github.io/wright-tiktok-drafts/01.jpg','https://ceomo30-lab.github.io/wright-tiktok-drafts/02.jpg','https://ceomo30-lab.github.io/wright-tiktok-drafts/03.jpg','https://ceomo30-lab.github.io/wright-tiktok-drafts/04.jpg','https://ceomo30-lab.github.io/wright-tiktok-drafts/05.jpg']};const history=h.posts.some(x=>x.id===existing.id)?h.posts:[existing,...h.posts];return json({account:{open_id:s.open_id||null,scope:s.scope||''},posts:q.posts||[],history})}
async function addHistory(env,item){const h=await env.POSTS.get('history','json')||{posts:[]};h.posts=[item,...h.posts.filter(x=>x.id!==item.id)].slice(0,200);await env.POSTS.put('history',JSON.stringify(h))}
async function queueList(s,env){await complianceMigration(env);await ensureWright02(env);await ensureWright03(env);await ensureWright04(env);const data=await ensureWright05(env);return json({posts:data.posts.filter(p=>p.state==='ready').map(p=>({id:p.id,version:p.version,name:p.name,caption:p.caption,photo_images:p.photo_images,suggested_date:p.suggested_date,suggested_time:p.suggested_time,research:p.research||null}))})}
async function queueReorder(req,s,env){if(!sameOrigin(req))return json({error:'Bad origin'},403);const b=await req.json();if(!Array.isArray(b.ids)||new Set(b.ids).size!==b.ids.length)return json({error:'Invalid order'},400);const q=await env.POSTS.get('queue','json')||{posts:[]},rank=new Map(b.ids.map((id,i)=>[id,i]));q.posts.sort((a,b)=>(rank.get(a.id)??9999)-(rank.get(b.id)??9999));await env.POSTS.put('queue',JSON.stringify(q));return json({ordered:b.ids.length})}
async function queueApprove(req,s,env){const b=await req.json();if(b.batch_consent!==true||!Array.isArray(b.posts)||!b.posts.length)return json({error:'Select and review at least one exact post'},400);const ci=await tt('/v2/post/publish/creator_info/query/',{},s);if(!ci.ok)return json({error:'Could not refresh TikTok creator options'},400);const available=ci.body.data?.privacy_level_options||[],queue=await env.POSTS.get('queue','json')||{posts:[]},approved=[];for(const choice of b.posts){const p=queue.posts.find(x=>x.id===choice.id);if(!p||p.state!=='ready'||p.version!==choice.version)return json({error:'A selected post changed. Review the updated version.'},409);if(choice.explicit_post_consent!==true||!available.includes(choice.privacy_level))return json({error:'Each post needs exact consent and a currently available privacy choice'},400);if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(choice.scheduled_at_local||''))return json({error:'Each post needs a visible scheduled date and time'},400);p.approval={...choice,approved_at:new Date().toISOString(),approved_by_open_id:s.open_id};p.state='approved';approved.push({id:p.id,version:p.version,scheduled_at_local:choice.scheduled_at_local,timezone:choice.timezone})}await env.POSTS.put('queue',JSON.stringify(queue));return json({approved})}
async function revoke(s,env){await fetch(TT+'/v2/oauth/revoke/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,client_secret:env.TIKTOK_CLIENT_SECRET,token:s.access_token})});await env.SESSIONS.delete('session:'+s._id);return json({revoked:true})}
async function getSession(req,env){const x=cookies(req).session;if(!x)return null;let s=await env.SESSIONS.get('session:'+x,'json');if(s){s._id=x;if(s.expires_at&&Date.now()>s.expires_at*1000-300000)s=await refreshSession(env,s,x)}return s}
async function refreshSession(env,s,id){if(!s.refresh_token)return null;const r=await fetch(TT+'/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,client_secret:env.TIKTOK_CLIENT_SECRET,grant_type:'refresh_token',refresh_token:s.refresh_token})}),x=await r.json();if(!r.ok||!x.access_token)return null;await env.SESSIONS.put('session:'+id,JSON.stringify(x),{expirationTtl:x.refresh_expires_in||31536000});await savePrimaryAccount(env,x);x._id=id;return x}
async function tt(path,body,s){const r=await fetch(TT+path,{method:'POST',headers:{authorization:'Bearer '+s.access_token,'content-type':'application/json; charset=UTF-8'},body:JSON.stringify(body)});return {ok:r.ok,body:await r.json()}}
async function rate(req,env,kind,max){const ip=req.headers.get('cf-connecting-ip')||'unknown',bucket=Math.floor(Date.now()/60000),key=`rate:${kind}:${ip}:${bucket}`,n=+(await env.SESSIONS.get(key)||0);if(n>=max)return false;await env.SESSIONS.put(key,String(n+1),{expirationTtl:120});return true}
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store'}}),cookies=req=>Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2)),cookie=(k,v,age)=>`${k}=${encodeURIComponent(v)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`,id=n=>[...crypto.getRandomValues(new Uint8Array(n))].map(x=>x.toString(16).padStart(2,'0')).join(''),validId=x=>typeof x==='string'&&/^[a-f0-9]{32,128}$/.test(x),sha=async x=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x)))].map(v=>v.toString(16).padStart(2,'0')).join(''),safeEq=(a,b)=>{if(!a||!b||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0},sameOrigin=req=>{const o=req.headers.get('origin');return !o||o===new URL(req.url).origin},b64=x=>btoa(String.fromCharCode(...x)),unb64=x=>Uint8Array.from(atob(x),c=>c.charCodeAt(0)),html=(body,status=200)=>new Response(`<!doctype html><meta name="viewport" content="width=device-width"><title>Wright Drafts</title><style>body{font:17px system-ui;max-width:620px;margin:12vh auto;padding:24px;color:#182321}h1{font-size:34px}.btn{display:inline-block;padding:14px 20px;background:#245f55;color:white;border-radius:10px;text-decoration:none}</style>${body}`,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
