// Cloudflare Worker reference backend for Wright Drafts Direct Post.
// Secrets: TIKTOK_CLIENT_KEY, TIKTOK_CLIENT_SECRET; bindings: SESSIONS (KV), POSTS (KV).
const TT='https://open.tiktokapis.com';
export default {async fetch(req,env){const u=new URL(req.url);try{
 if(u.pathname==='/api/tiktok/oauth/start')return oauthStart(req,env);
 if(u.pathname==='/api/tiktok/oauth/callback')return oauthCallback(req,env);
 const session=await getSession(req,env);if(!session)return json({error:'Connect TikTok first'},401);
 if(u.pathname==='/api/tiktok/creator-info'&&req.method==='GET')return creatorInfo(session,env);
 if(u.pathname==='/api/tiktok/direct-post'&&req.method==='POST')return directPost(req,session,env);
 if(u.pathname==='/api/tiktok/status'&&req.method==='GET')return postStatus(u,session,env);
 if(u.pathname==='/api/tiktok/revoke'&&req.method==='POST')return revoke(session,env);
 return env.ASSETS.fetch(req);
 }catch(e){return json({error:'Request failed'},500)}}};
async function oauthStart(req,env){const state=crypto.randomUUID(),sid=crypto.randomUUID();await env.SESSIONS.put('oauth:'+sid,JSON.stringify({state}),{expirationTtl:600});const redirect=new URL('/api/tiktok/oauth/callback',req.url).href;const q=new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,scope:'user.info.basic,video.publish,video.upload',response_type:'code',redirect_uri:redirect,state});return new Response(null,{status:302,headers:{location:'https://www.tiktok.com/v2/auth/authorize/?'+q,'set-cookie':cookie('oauth',sid,600)}})}
async function oauthCallback(req,env){const u=new URL(req.url),sid=cookies(req).oauth,rec=sid&&await env.SESSIONS.get('oauth:'+sid,'json');if(!rec||rec.state!==u.searchParams.get('state'))return json({error:'Invalid OAuth state'},400);const redirect=new URL('/api/tiktok/oauth/callback',req.url).href;const form=new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,client_secret:env.TIKTOK_CLIENT_SECRET,code:u.searchParams.get('code'),grant_type:'authorization_code',redirect_uri:redirect});const r=await fetch(TT+'/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});const tok=await r.json();if(!r.ok||!tok.access_token)return json({error:'TikTok authorization failed'},400);const sessionId=crypto.randomUUID();await env.SESSIONS.put('session:'+sessionId,JSON.stringify(tok),{expirationTtl:tok.refresh_expires_in||31536000});return new Response(null,{status:302,headers:{location:'/direct-post-ui/', 'set-cookie':cookie('session',sessionId,tok.refresh_expires_in||31536000)}})}
async function creatorInfo(s){const r=await tt('/v2/post/publish/creator_info/query/',{},s);return json(r.body,r.ok?200:400)}
async function directPost(req,s,env){const b=await req.json();if(b.consent!==true||!b.privacy_level)return json({error:'Exact post approval and privacy choice are required'},400);const ci=await tt('/v2/post/publish/creator_info/query/',{},s);if(!ci.ok||!ci.body.data?.privacy_level_options?.includes(b.privacy_level))return json({error:'Privacy choice is not currently available'},400);if(b.brand_content_toggle&&b.privacy_level==='SELF_ONLY')return json({error:'Branded content cannot be private'},400);const manifest=await env.POSTS.get('current','json');if(!manifest||manifest.approved!==true)return json({error:'No finished carousel is loaded'},409);const payload={media_type:'PHOTO',post_mode:'DIRECT_POST',is_aigc:!!manifest.is_aigc,post_info:{title:manifest.title||'',description:b.caption||'',privacy_level:b.privacy_level,disable_comment:!!b.disable_comment,auto_add_music:!!b.auto_add_music,brand_content_toggle:!!b.brand_content_toggle,brand_organic_toggle:!!b.brand_organic_toggle},source_info:{source:'PULL_FROM_URL',photo_cover_index:manifest.cover_index||0,photo_images:manifest.photo_images}};const out=await tt('/v2/post/publish/content/init/',payload,s);return json(out.ok?{publish_id:out.body.data?.publish_id}:out.body,out.ok?200:400)}
async function postStatus(u,s){const id=u.searchParams.get('publish_id');if(!id)return json({error:'publish_id required'},400);const out=await tt('/v2/post/publish/status/fetch/',{publish_id:id},s);const status=out.body.data?.status||out.body.error?.message;return json({status,done:['PUBLISH_COMPLETE','FAILED'].includes(status),raw:out.body},out.ok?200:400)}
async function revoke(s,env){await fetch(TT+'/v2/oauth/revoke/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,client_secret:env.TIKTOK_CLIENT_SECRET,token:s.access_token})});await env.SESSIONS.delete('session:'+s._id);return json({revoked:true})}
async function getSession(req,env){const id=cookies(req).session;if(!id)return null;const s=await env.SESSIONS.get('session:'+id,'json');if(s)s._id=id;return s}
async function tt(path,body,s){const r=await fetch(TT+path,{method:'POST',headers:{authorization:'Bearer '+s.access_token,'content-type':'application/json; charset=UTF-8'},body:JSON.stringify(body)});return {ok:r.ok,body:await r.json()}}
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const cookies=req=>Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2));
const cookie=(k,v,age)=>`${k}=${encodeURIComponent(v)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
