// Wright Drafts Direct Post backend. Secrets: TIKTOK_CLIENT_KEY, TIKTOK_CLIENT_SECRET.
const TT='https://open.tiktokapis.com',PAIR_TTL=600;
export default {async fetch(req,env){const u=new URL(req.url);try{
 if(u.pathname==='/api/pair/create'&&req.method==='POST')return pairCreate(req,env);
 if(u.pathname==='/api/pair/claim'&&req.method==='POST')return pairClaim(req,env);
 if(u.pathname==='/pair/desktop'&&req.method==='GET')return pairDesktop(u);
 if(u.pathname==='/api/pair/oauth/start'&&req.method==='GET')return pairOauthStart(req,env);
 if(u.pathname==='/api/tiktok/oauth/start')return oauthStart(req,env);
 if(u.pathname==='/api/tiktok/oauth/callback')return oauthCallback(req,env);
 if(req.method==='GET'&&!u.pathname.startsWith('/api/'))return fetch('https://ceomo30-lab.github.io/wright-tiktok-drafts'+u.pathname+u.search);
 const session=await getSession(req,env);if(!session)return json({error:'Connect TikTok first'},401);
 if(u.pathname==='/api/tiktok/creator-info'&&req.method==='GET')return creatorInfo(session);
 if(u.pathname==='/api/tiktok/direct-post'&&req.method==='POST')return directPost(req,session,env);
 if(u.pathname==='/api/tiktok/status'&&req.method==='GET')return postStatus(u,session);
 if(u.pathname==='/api/tiktok/revoke'&&req.method==='POST')return revoke(session,env);
 if(u.pathname==='/api/workspace'&&req.method==='GET')return workspace(session,env);
 if(u.pathname==='/api/seed/wright-02'&&req.method==='POST')return seedWright02(req,session,env);
 if(u.pathname==='/api/queue'&&req.method==='GET')return queueList(session,env);
 if(u.pathname==='/api/queue/approve'&&req.method==='POST')return queueApprove(req,session,env);
 return json({error:'Not found'},404);
 }catch(e){console.error(e);return json({error:'Request failed'},500)}}};

export class PairCoordinator{constructor(state){this.state=state}async fetch(req){const u=new URL(req.url),now=Date.now();if(req.method==='POST'&&u.pathname==='/init'){const b=await req.json(),old=await this.state.storage.get('pair');if(old&&old.expires>now)return json({error:'Pair already exists'},409);await this.state.storage.put('pair',{claim_hash:b.claim_hash,expires:now+PAIR_TTL*1000,status:'pending'});await this.state.storage.setAlarm(now+PAIR_TTL*1000);return json({ok:true})}if(req.method==='POST'&&u.pathname==='/complete'){const b=await req.json(),p=await this.state.storage.get('pair');if(!p||p.expires<=now||p.status!=='pending')return json({error:'Pair unavailable'},409);p.status='complete';p.token=b.token;await this.state.storage.put('pair',p);return json({ok:true})}if(req.method==='POST'&&u.pathname==='/claim'){const b=await req.json(),p=await this.state.storage.get('pair');if(!p||p.expires<=now||p.status!=='complete'||!safeEq(p.claim_hash,b.claim_hash))return json({error:'Pair not ready'},409);const token=p.token;await this.state.storage.deleteAll();return json({token})}return json({error:'Not found'},404)}async alarm(){await this.state.storage.deleteAll()}}

async function pairCreate(req,env){if(!sameOrigin(req))return json({error:'Bad origin'},403);if(!await rate(req,env,'create',5))return json({error:'Too many pairing attempts'},429);const pair=id(24),secret=id(32),hash=await sha(secret),stub=env.PAIR_COORDINATOR.getByName(pair);const r=await stub.fetch('https://pair/init',{method:'POST',body:JSON.stringify({claim_hash:hash})});if(!r.ok)return json({error:'Could not create pair'},409);const base=new URL(req.url).origin;return json({pair_id:pair,claim_secret:secret,desktop_url:`${base}/pair/desktop?pair=${encodeURIComponent(pair)}`,expires_in:PAIR_TTL})}
async function pairClaim(req,env){if(!sameOrigin(req))return json({error:'Bad origin'},403);if(!await rate(req,env,'claim',30))return json({error:'Too many claim attempts'},429);const b=await req.json();if(!validId(b.pair_id)||!validId(b.claim_secret))return json({error:'Invalid pair'},400);const stub=env.PAIR_COORDINATOR.getByName(b.pair_id),r=await stub.fetch('https://pair/claim',{method:'POST',body:JSON.stringify({claim_hash:await sha(b.claim_secret)})});if(!r.ok)return json({pending:true},202);const out=await r.json(),sessionId=id(32);await env.SESSIONS.put('session:'+sessionId,JSON.stringify(out.token),{expirationTtl:out.token.refresh_expires_in||31536000});return new Response(JSON.stringify({connected:true}),{headers:{'content-type':'application/json','cache-control':'no-store','set-cookie':cookie('session',sessionId,out.token.refresh_expires_in||31536000)}})}
function pairDesktop(u){const p=u.searchParams.get('pair');if(!validId(p))return html('<h1>Invalid or expired link</h1>',400);return html(`<main><p>WRIGHT DRAFTS</p><h1>Connect TikTok on this computer</h1><p>This one-time link expires in 10 minutes. Your TikTok tokens never appear in this link.</p><a class="btn" href="/api/pair/oauth/start?pair=${encodeURIComponent(p)}">Continue with TikTok</a></main>`)}
async function pairOauthStart(req,env){const u=new URL(req.url),pair=u.searchParams.get('pair');if(!validId(pair)||!await rate(req,env,'oauth',10))return html('<h1>Invalid or expired link</h1>',400);const state=id(32),redirect=new URL('/api/tiktok/oauth/callback',req.url).href;await env.SESSIONS.put('pair-state:'+state,JSON.stringify({pair,redirect}),{expirationTtl:PAIR_TTL});const q=new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,scope:'user.info.basic,video.publish,video.upload',response_type:'code',redirect_uri:redirect,state,disable_auto_auth:'1'});return Response.redirect('https://www.tiktok.com/v2/auth/authorize/?'+q,302)}
async function oauthStart(req,env){const state=crypto.randomUUID(),sid=crypto.randomUUID();await env.SESSIONS.put('oauth:'+sid,JSON.stringify({state}),{expirationTtl:600});const redirect=new URL('/api/tiktok/oauth/callback',req.url).href;const q=new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,scope:'user.info.basic,video.publish,video.upload',response_type:'code',redirect_uri:redirect,state,disable_auto_auth:'1'});return new Response(null,{status:302,headers:{location:'https://www.tiktok.com/v2/auth/authorize/?'+q,'set-cookie':cookie('oauth',sid,600)}})}
async function oauthCallback(req,env){const u=new URL(req.url),state=u.searchParams.get('state'),pairRec=state&&await env.SESSIONS.get('pair-state:'+state,'json');if(pairRec){await env.SESSIONS.delete('pair-state:'+state);const tok=await exchange(u,env,pairRec.redirect);if(tok.error)return json(tok,400);const r=await env.PAIR_COORDINATOR.getByName(pairRec.pair).fetch('https://pair/complete',{method:'POST',body:JSON.stringify({token:tok})});return r.ok?html('<main><h1>TikTok connected</h1><p>Return to your phone. This window can be closed.</p></main>'):html('<h1>This link expired</h1>',409)}const sid=cookies(req).oauth,rec=sid&&await env.SESSIONS.get('oauth:'+sid,'json');if(!rec||rec.state!==state)return json({error:'Invalid OAuth state'},400);const redirect=new URL('/api/tiktok/oauth/callback',req.url).href,tok=await exchange(u,env,redirect);if(tok.error)return json(tok,400);const sessionId=id(32);await env.SESSIONS.put('session:'+sessionId,JSON.stringify(tok),{expirationTtl:tok.refresh_expires_in||31536000});return new Response(null,{status:302,headers:{location:'/direct-post-ui/','set-cookie':cookie('session',sessionId,tok.refresh_expires_in||31536000)}})}
async function exchange(u,env,redirect){const form=new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,client_secret:env.TIKTOK_CLIENT_SECRET,code:u.searchParams.get('code')||'',grant_type:'authorization_code',redirect_uri:redirect});const r=await fetch(TT+'/v2/oauth/token/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});const x=await r.json();return r.ok&&x.access_token?x:{error:'TikTok authorization failed'}}
async function creatorInfo(s){const r=await tt('/v2/post/publish/creator_info/query/',{},s);return json(r.body,r.ok?200:400)}
async function directPost(req,s,env){const b=await req.json();if(b.consent!==true||!b.privacy_level)return json({error:'Exact post approval and privacy choice are required'},400);const ci=await tt('/v2/post/publish/creator_info/query/',{},s);if(!ci.ok||!ci.body.data?.privacy_level_options?.includes(b.privacy_level))return json({error:'Privacy choice is not currently available'},400);if(b.brand_content_toggle&&b.privacy_level==='SELF_ONLY')return json({error:'Branded content cannot be private'},400);const manifest=await env.POSTS.get('current','json');if(!manifest||manifest.approved!==true)return json({error:'No finished carousel is loaded'},409);const payload={media_type:'PHOTO',post_mode:'DIRECT_POST',is_aigc:!!manifest.is_aigc,post_info:{title:manifest.title||'',description:b.caption||'',privacy_level:b.privacy_level,disable_comment:!!b.disable_comment,auto_add_music:!!b.auto_add_music,brand_content_toggle:!!b.brand_content_toggle,brand_organic_toggle:!!b.brand_organic_toggle},source_info:{source:'PULL_FROM_URL',photo_cover_index:manifest.cover_index||0,photo_images:manifest.photo_images}};const out=await tt('/v2/post/publish/content/init/',payload,s);if(out.ok){const pid=out.body.data?.publish_id;await addHistory(env,{id:'publish-'+pid,name:manifest.name||manifest.title||'TikTok carousel',caption:b.caption||'',state:'processing',submitted_at:new Date().toISOString(),publish_id:pid,photo_images:manifest.photo_images,privacy_level:b.privacy_level,auto_add_music:!!b.auto_add_music});}return json(out.ok?{publish_id:out.body.data?.publish_id}:out.body,out.ok?200:400)}
async function postStatus(u,s){const id=u.searchParams.get('publish_id');if(!id)return json({error:'publish_id required'},400);const out=await tt('/v2/post/publish/status/fetch/',{publish_id:id},s),status=out.body.data?.status||out.body.error?.message;return json({status,done:['PUBLISH_COMPLETE','FAILED'].includes(status),raw:out.body},out.ok?200:400)}
async function ensureWright02(env){const q=await env.POSTS.get('queue','json')||{posts:[]},id='wright-02-ai-steering';if(!q.posts.some(x=>x.id===id)){q.posts.unshift({id,version:'v1-2026-09-18T2306PDT',name:'AI autopilot vs. AI engine',caption:'AI helping a teen finish faster is not the same as a teen learning to think better. The difference is who makes the calls: defining the problem, directing the tool, testing the result, and choosing what happens next. Wright gives teens repeated practice steering.\n\n#ParentingTeens #AILiteracy #FutureSkills #WrightSchool',state:'ready',photo_images:['https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-01.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-02.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-03.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-04.png','https://ceomo30-lab.github.io/wright-tiktok-drafts/media/wright-02/wright-02-05.png'],suggested_date:'2026-09-19',suggested_time:'12:00',research:{thesis:'The important difference is not AI access but whether the teen retains judgment.',sources:['https://www.unesco.org/en/articles/what-you-need-know-about-unescos-new-ai-competency-frameworks-students-and-teachers','https://www.oecd.org/en/about/projects/pisa-2029-media-and-artificial-intelligence-literacy.html','https://www.commonsensemedia.org/research/the-dawn-of-the-ai-era-teens-parents-and-the-adoption-of-generative-ai-at-home-and-school','https://www.microsoft.com/en-us/research/wp-content/uploads/2025/01/lee_2025_ai_critical_thinking_survey.pdf','https://wright.school/program']}});await env.POSTS.put('queue',JSON.stringify(q))}return q}
async function seedWright02(req,s,env){if(!sameOrigin(req))return json({error:'Bad origin'},403);const q=await ensureWright02(env);return json({created:true,id:'wright-02-ai-steering'})}
async function workspace(s,env){const q=await ensureWright02(env),h=await env.POSTS.get('history','json')||{posts:[]};const existing={id:'posted-2026-09-18-ai-assignment',name:'AI can finish the assignment',caption:'',state:'published',published_at:'2026-09-18T19:45:00-07:00',publish_id:'p_inbox_url~v2.7687070275556755470',photo_images:['https://ceomo30-lab.github.io/wright-tiktok-drafts/01.jpg','https://ceomo30-lab.github.io/wright-tiktok-drafts/02.jpg','https://ceomo30-lab.github.io/wright-tiktok-drafts/03.jpg','https://ceomo30-lab.github.io/wright-tiktok-drafts/04.jpg','https://ceomo30-lab.github.io/wright-tiktok-drafts/05.jpg']};const history=h.posts.some(x=>x.id===existing.id)?h.posts:[existing,...h.posts];return json({account:{open_id:s.open_id||null,scope:s.scope||''},posts:q.posts||[],history})}
async function addHistory(env,item){const h=await env.POSTS.get('history','json')||{posts:[]};h.posts=[item,...h.posts.filter(x=>x.id!==item.id)].slice(0,200);await env.POSTS.put('history',JSON.stringify(h))}
async function queueList(s,env){const data=await ensureWright02(env);return json({posts:data.posts.filter(p=>p.state==='ready').map(p=>({id:p.id,version:p.version,name:p.name,caption:p.caption,photo_images:p.photo_images,suggested_date:p.suggested_date,suggested_time:p.suggested_time}))})}
async function queueApprove(req,s,env){const b=await req.json();if(b.batch_consent!==true||!Array.isArray(b.posts)||!b.posts.length)return json({error:'Select and review at least one exact post'},400);const ci=await tt('/v2/post/publish/creator_info/query/',{},s);if(!ci.ok)return json({error:'Could not refresh TikTok creator options'},400);const available=ci.body.data?.privacy_level_options||[],queue=await env.POSTS.get('queue','json')||{posts:[]},approved=[];for(const choice of b.posts){const p=queue.posts.find(x=>x.id===choice.id);if(!p||p.state!=='ready'||p.version!==choice.version)return json({error:'A selected post changed. Review the updated version.'},409);if(choice.explicit_post_consent!==true||!available.includes(choice.privacy_level))return json({error:'Each post needs exact consent and a currently available privacy choice'},400);if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(choice.scheduled_at_local||''))return json({error:'Each post needs a visible scheduled date and time'},400);p.approval={...choice,approved_at:new Date().toISOString(),approved_by_open_id:s.open_id};p.state='approved';approved.push({id:p.id,version:p.version,scheduled_at_local:choice.scheduled_at_local,timezone:choice.timezone})}await env.POSTS.put('queue',JSON.stringify(queue));return json({approved})}
async function revoke(s,env){await fetch(TT+'/v2/oauth/revoke/',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:env.TIKTOK_CLIENT_KEY,client_secret:env.TIKTOK_CLIENT_SECRET,token:s.access_token})});await env.SESSIONS.delete('session:'+s._id);return json({revoked:true})}
async function getSession(req,env){const x=cookies(req).session;if(!x)return null;const s=await env.SESSIONS.get('session:'+x,'json');if(s)s._id=x;return s}
async function tt(path,body,s){const r=await fetch(TT+path,{method:'POST',headers:{authorization:'Bearer '+s.access_token,'content-type':'application/json; charset=UTF-8'},body:JSON.stringify(body)});return {ok:r.ok,body:await r.json()}}
async function rate(req,env,kind,max){const ip=req.headers.get('cf-connecting-ip')||'unknown',bucket=Math.floor(Date.now()/60000),key=`rate:${kind}:${ip}:${bucket}`,n=+(await env.SESSIONS.get(key)||0);if(n>=max)return false;await env.SESSIONS.put(key,String(n+1),{expirationTtl:120});return true}
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store'}}),cookies=req=>Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2)),cookie=(k,v,age)=>`${k}=${encodeURIComponent(v)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`,id=n=>[...crypto.getRandomValues(new Uint8Array(n))].map(x=>x.toString(16).padStart(2,'0')).join(''),validId=x=>typeof x==='string'&&/^[a-f0-9]{32,128}$/.test(x),sha=async x=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x)))].map(v=>v.toString(16).padStart(2,'0')).join(''),safeEq=(a,b)=>{if(!a||!b||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0},sameOrigin=req=>{const o=req.headers.get('origin');return !o||o===new URL(req.url).origin},html=(body,status=200)=>new Response(`<!doctype html><meta name="viewport" content="width=device-width"><title>Wright Drafts</title><style>body{font:17px system-ui;max-width:620px;margin:12vh auto;padding:24px;color:#182321}h1{font-size:34px}.btn{display:inline-block;padding:14px 20px;background:#245f55;color:white;border-radius:10px;text-decoration:none}</style>${body}`,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
